# Clonamos el repositorio para obtener los dataSet

In [10]:
!git clone https://github.com/joanby/machinelearning-az.git

fatal: destination path 'machinelearning-az' already exists and is not an empty directory.


# Damos acceso a nuestro Drive

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Test it

In [4]:
!ls '/content/drive/My Drive'

'1.-Guía Conamat UNAM 5ta. Edición.pdf'
'2024-10-24 18-17-54.mp4'
 Actuaria
'CALL AND PUT.gdoc'
'Certificación JUAN MIGUEL GALAN OLIVARES - Excel 2013 Academic.pdf'
'Certificación JUAN MIGUEL GALAN OLIVARES - Power Point 2013 Academic.pdf'
'Certificación JUAN MIGUEL GALAN OLIVARES - Word 2013 Academic.pdf'
'Certificado de Vacunacion Covid-19 GAOJ030323HMCLLNA8.pdf'
 Classroom
'Colab Notebooks'
'Conceptos IDO Tarea.gdoc'
 constancia_diplomado_finanzas.pdf
'CONTRATO FIRMADO-JUANMIGUEL GALAN OLIVARES (1).pdf'
'CONTRATO FIRMADO-JUANMIGUEL GALAN OLIVARES.pdf'
'Copia de Horario para Quemados.gform'
'David Paper Craft por Santi.pdf'
'Demorafia 30-09-2024.mp4'
'Diegrama de la matriz.gdoc'
'Documento sin título (1).gdoc'
'Documento sin título (2).gdoc'
'Documento sin título (3).gdoc'
'Documento sin título (4).gdoc'
'Documento sin título (5).gdoc'
'Documento sin título (6).gdoc'
'Documento sin título (7).gdoc'
'Documento sin título (8).gdoc'
'Documento sin título (9).gdoc'
'Documen

#Google colab tools

In [5]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

#Instalar dependendias

In [11]:
!pip install sklearn

  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


# Regresión Lineal Múltiple


# Cómo importar las librerías


In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [27]:
dataset = pd.read_csv('https://raw.githubusercontent.com/JuanMi-Galan/machinelearning-az/refs/heads/master/original/Part%202%20-%20Regression/Section%205%20-%20Multiple%20Linear%20Regression/50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values


# Codificar datos categóricos

In [28]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import make_column_transformer
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = make_column_transformer((OneHotEncoder(), [3]), remainder = "passthrough")
X = onehotencoder.fit_transform(X)

# Evitar la trampa de las variables ficticias


In [29]:
X = X[:, 1:] #Evita la multicolinealidad

# Dividir el data set en conjunto de entrenamiento y conjunto de testing


In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [32]:
"""
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
"""

'\nfrom sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nX_train = sc_X.fit_transform(X_train)\nX_test = sc_X.transform(X_test)\n'

# Ajustar el modelo de Regresión lineal múltiple con el conjunto de entrenamiento


In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression()

# Predicción de los resultados en el conjunto de testing


In [35]:
y_pred = regression.predict(X_test)

In [36]:
y_pred

array([103015.20159796, 132582.27760816, 132447.73845175,  71976.09851259,
       178537.48221054, 116161.24230163,  67851.69209676,  98791.73374688,
       113969.43533012, 167921.0656955 ])

In [37]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

# Construir el modelo óptimo de RLM utilizando la Eliminación hacia atrás

In [38]:
import statsmodels.api as sm
X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1) # Le agrego a la columna de unos la matriz X.
SL = 0.05

In [39]:
X

array([[1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1, 1.0, 0.0, 9

#Se ha añadido el modificador .tolist() al X_opt para adaptarse a Python 3.7

In [ ]:
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
regression_OLS.summary()

X_opt = X[:, [0, 1, 3, 4, 5]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
regression_OLS.summary()

X_opt = X[:, [0, 3, 4, 5]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
regression_OLS.summary()

X_opt = X[:, [0, 3, 5]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
regression_OLS.summary()

X_opt = X[:, [0, 3]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
regression_OLS.summary()